# Generated by Django 5.2.17 on 2026-08-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(max_length=30, unique=True)),
                ('tipo', models.CharField(choices=[('NOTEBOOK', 'Notebook'), ('ESCRITORIO', 'PC de escritorio'), ('IMPRESORA', 'Impresora'), ('SERVIDOR', 'Servidor'), ('RED', 'Equipo de red'), ('OTRO', 'Otro')], db_index=True, max_length=12)),
                ('marca', models.CharField(max_length=60)),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('numero_serie', models.CharField(blank=True, max_length=80)),
                ('ubicacion', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('EN_REPARACION', 'En reparacion'), ('BAJA', 'Dado de baja')], db_index=True, default='OPERATIVO', max_length=14)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'equipo',
                'verbose_name_plural': 'equipos',
                'ordering': ['codigo_interno'],
            },
        ),
    ]
