# Generated by Django 5.2.17 on 2026-08-31 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Persona que usa habitualmente el equipo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_a_cargo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['tipo', 'estado'], name='equipos_equ_tipo_cf89ef_idx'),
        ),
    ]
