# Generated by Django 5.2.17 on 2026-08-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', models.TextField()),
                ('es_interno', models.BooleanField(default=False, help_text='Solo visible para tecnicos y administradores.')),
                ('es_sistema', models.BooleanField(default=False, help_text='Generado automaticamente por un cambio de estado.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
                'ordering': ['creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software'), ('RED', 'Red y conectividad'), ('ACCESOS', 'Accesos y cuentas'), ('OTRO', 'Otro')], db_index=True, default='OTRO', max_length=10)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Critica')], db_index=True, default='MEDIA', max_length=8)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PROGRESO', 'En progreso'), ('EN_ESPERA', 'En espera de terceros'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado')], db_index=True, default='ABIERTO', max_length=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cerrado_en', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'ordering': ['-creado_en'],
            },
        ),
    ]
